spring.application.name=ParkingSystem


#Informacion general DB
spring.datasource.url=jdbc:h2:mem:parkinsystem_db
spring.datasource.username=sa
spring.datasource.password=

#Activacion H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Activacion JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true 