spring.application.name=ParkingSystem


#Informacion general DB
spring.datasource.url=jdbc:h2:mem:parkinsystem_db
spring.datasource.username=sa
spring.datasource.password=

#Activacion H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Activacion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 

# Ruta absoluta al ejecutable de Python dentro del entorno virtual
python.executable.path=C:/Users/USER/Documents/Desarrollo de Software/ProyectoIntegrador/ParkingSystem/Analytics/venv/Scripts/python.exe

# Ruta absoluta al script principal
analytics.script.path=C:/Users/USER/Documents/Desarrollo de Software/ProyectoIntegrador/ParkingSystem/Analytics/main.py

# Ruta absoluta a la carpeta de salida (opcional, pero ayuda)
analytics.output.path=C:/Users/USER/Documents/Desarrollo de Software/ProyectoIntegrador/ParkingSystem/Analytics/outputs

#Tiempo máximo de ejecución del script de Analytics (en segundos)
analytics.script.timeout=60